"""Adds new table to the database

Revision ID: 09d7b438569e
Revises: 5aa536ad5924
Create Date: 2020-05-14 19:42:18.582198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d7b438569e'
down_revision = '5aa536ad5924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identification', sa.Integer(), nullable=True),
    sa.Column('FullName', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.identification'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipient_email'), 'receipient', ['email'], unique=True)
    op.create_index(op.f('ix_receipient_id'), 'receipient', ['id'], unique=False)
    op.create_index(op.f('ix_receipient_identification'), 'receipient', ['identification'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipient_identification'), table_name='receipient')
    op.drop_index(op.f('ix_receipient_id'), table_name='receipient')
    op.drop_index(op.f('ix_receipient_email'), table_name='receipient')
    op.drop_table('receipient')
    # ### end Alembic commands ###
