"""changed payment name characterisitc on users

Revision ID: 252dfcfc6571
Revises: a19f877bc006
Create Date: 2020-05-13 15:03:58.650130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252dfcfc6571'
down_revision = 'a19f877bc006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payment_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['contactNumber'])
    op.drop_constraint('users_payment_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'payment', ['payment_name'], ['name'])
    op.drop_column('users', 'payment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_payment_id_fkey', 'users', 'payment', ['payment_id'], ['id'])
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'payment_name')
    # ### end Alembic commands ###
