"""Updated Schemato to remove weight

Revision ID: 3a386222058a
Revises: c8b16b67f95b
Create Date: 2020-05-14 17:00:41.759487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a386222058a'
down_revision = 'c8b16b67f95b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'weight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
