"""Updated Schemato to add weight

Revision ID: 5aa536ad5924
Revises: 3a386222058a
Create Date: 2020-05-14 17:01:12.246846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa536ad5924'
down_revision = '3a386222058a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('weight', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'weight')
    # ### end Alembic commands ###
