"""Updated Schema

Revision ID: c8b16b67f95b
Revises: 799ebef95103
Create Date: 2020-05-14 14:56:05.281704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b16b67f95b'
down_revision = '799ebef95103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('DeliveryTypename', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('NumberOfItem', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('ParcelTypename', sa.String(), nullable=True))
    op.drop_constraint('orders_ParcelTypeid_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_DeliveryTypeid_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'delivery', ['DeliveryTypename'], ['name'])
    op.create_foreign_key(None, 'orders', 'parcel', ['ParcelTypename'], ['name'])
    op.drop_column('orders', 'DeliveryTypeid')
    op.drop_column('orders', 'ParcelTypeid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ParcelTypeid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('DeliveryTypeid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_DeliveryTypeid_fkey', 'orders', 'delivery', ['DeliveryTypeid'], ['id'])
    op.create_foreign_key('orders_ParcelTypeid_fkey', 'orders', 'parcel', ['ParcelTypeid'], ['id'])
    op.drop_column('orders', 'ParcelTypename')
    op.drop_column('orders', 'NumberOfItem')
    op.drop_column('orders', 'DeliveryTypename')
    # ### end Alembic commands ###
